# Generated by Django 3.1.2 on 2020-10-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('trainer', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('groups', models.ManyToManyField(to='blackbelt.Group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(choices=[(1, 'BIAŁY'), (2, 'BIAŁY 1'), (3, 'BIAŁY 2'), (4, 'BIAŁY 3'), (5, 'BIAŁY 4'), (6, 'NIEBIECKI'), (7, 'NIEBIESKI 1'), (8, 'NIEBIESKI 2'), (9, 'NIEBIESKI 3'), (10, 'NIEBIESKI 4'), (11, 'PURPUROWY'), (12, 'PURPUROWY 1'), (13, 'PURPUROWY 2'), (14, 'PURPUROWY 3'), (15, 'PURPUROWY 4'), (16, 'BRĄZOWY'), (17, 'BRĄZOWY 1'), (18, 'BRĄZOWY 2'), (19, 'BRĄZOWY 3'), (20, 'BRĄZOWY 4'), (21, 'CZARNY')], default=1, max_length=64)),
                ('promotion_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackbelt.student')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.BooleanField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackbelt.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackbelt.student')),
            ],
        ),
    ]
