# Generated by Django 3.1.2 on 2020-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbelt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='paid',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nazwa grupy'),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainer',
            field=models.CharField(max_length=64, verbose_name='Trener'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='month',
            field=models.DateField(verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(verbose_name='Adnotacje'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='studentbelt',
            name='belt',
            field=models.CharField(choices=[(1, 'BIAŁY'), (2, 'BIAŁY 1'), (3, 'BIAŁY 2'), (4, 'BIAŁY 3'), (5, 'BIAŁY 4'), (6, 'NIEBIECKI'), (7, 'NIEBIESKI 1'), (8, 'NIEBIESKI 2'), (9, 'NIEBIESKI 3'), (10, 'NIEBIESKI 4'), (11, 'PURPUROWY'), (12, 'PURPUROWY 1'), (13, 'PURPUROWY 2'), (14, 'PURPUROWY 3'), (15, 'PURPUROWY 4'), (16, 'BRĄZOWY'), (17, 'BRĄZOWY 1'), (18, 'BRĄZOWY 2'), (19, 'BRĄZOWY 3'), (20, 'BRĄZOWY 4'), (21, 'CZARNY')], default=1, max_length=64, verbose_name='Pas'),
        ),
        migrations.AlterField(
            model_name='studentbelt',
            name='promotion_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data otrzymania'),
        ),
    ]
