# Generated by Django 3.1.2 on 2020-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbelt', '0002_auto_20201009_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='belt',
            field=models.CharField(choices=[(1, 'BIAŁY'), (2, 'BIAŁY 1'), (3, 'BIAŁY 2'), (4, 'BIAŁY 3'), (5, 'BIAŁY 4'), (6, 'NIEBIECKI'), (7, 'NIEBIESKI 1'), (8, 'NIEBIESKI 2'), (9, 'NIEBIESKI 3'), (10, 'NIEBIESKI 4'), (11, 'PURPUROWY'), (12, 'PURPUROWY 1'), (13, 'PURPUROWY 2'), (14, 'PURPUROWY 3'), (15, 'PURPUROWY 4'), (16, 'BRĄZOWY'), (17, 'BRĄZOWY 1'), (18, 'BRĄZOWY 2'), (19, 'BRĄZOWY 3'), (20, 'BRĄZOWY 4'), (21, 'CZARNY')], default=1, max_length=64, verbose_name='Pas'),
        ),
        migrations.DeleteModel(
            name='StudentBelt',
        ),
    ]
